### ISSUE TITLE
Review the CSS styles and resubmit the exercise.

### ISSUE THREAD

**Issue by keikeka** [dedalovitor/InstgramPost_DV#1]
David! 

To approve the exercise has to look as similar to the example and in your case, you have to check the positions of the icons both in the header and the secondary icons below the image, that means if you use a displat flex, you have to place other properties to complement its position in the div, the padding also you have to check it. 

The HTML5 icon is too small, you must give it a size more according to the example, using font-size. 

Adjust the CSS and resubmit the project.

https://github.com/dedalovitor/InstgramPost_DV/blob/146c776324f95647571798ce2a362ecc7a67c8e7/styles.css#L5

**Comment by dedalovitor** [comment]
Hola Keili, ya he solucionado los fallos en la anterior versión y he subido la nueva.
Ya me dices
Sls
DV

**Comment by keikeka** [comment]
Perfect David! 

Approved your exercise! Good job!
